services:
  - type: web
    name: centro-estetico
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_SUPABASE_URL
        value: https://vcxykxvujwaarujusiry.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        value: sb_publishable_o8DGab0afKpBzOgopg1n1A_jF0-1b1I
